// examples/vite-react/src/main.tsx
import React from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'

createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>,
)

// examples/solid-js/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web'

import App from './App'
import PageA from './views/PageA'
import PageB from './views/PageB'

render(
  () => (
    <Router root={App}>
      <Route path="/list" component={PageA} />
      <Route path="/detail/:id" component={PageB} />
    </Router>
  ),
  document.getElementById('root') as HTMLElement,
)
